tabs fixed

diff --git a/code/src/org/ebiquity/data/collection/apktool/apktool b/code/src/org/ebiquity/data/collection/apktool/apktool
--- a/code/src/org/ebiquity/data/collection/apktool/apktool
+++ b/code/src/org/ebiquity/data/collection/apktool/apktool
@@ -6,7 +6,7 @@
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
-#     http://www.apache.org/licenses/LICENSE-2.0
+#	 http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
@@ -22,17 +22,17 @@
 # and set up progdir to be the fully-qualified pathname of its directory.
 prog="$0"
 while [ -h "${prog}" ]; do
-    newProg=`/bin/ls -ld "${prog}"`
-    echo ${newProg}
+	newProg=`/bin/ls -ld "${prog}"`
+	echo ${newProg}
 
 
-    newProg=`expr "${newProg}" : ".* -> \(.*\)$"`
-    if expr "x${newProg}" : 'x/' >/dev/null; then
-        prog="${newProg}"
-    else
-        progdir=`dirname "${prog}"`
-        prog="${progdir}/${newProg}"
-    fi
+	newProg=`expr "${newProg}" : ".* -> \(.*\)$"`
+	if expr "x${newProg}" : 'x/' >/dev/null; then
+		prog="${newProg}"
+	else
+		progdir=`dirname "${prog}"`
+		prog="${progdir}/${newProg}"
+	fi
 done
 oldwd=`pwd`
 progdir=`dirname "${prog}"`
@@ -46,8 +46,8 @@ jarfile=apktool.jar
 libdir="$progdir"
 if [ ! -r "$libdir/$jarfile" ]
 then
-    echo `basename "$prog"`": can't find $jarfile"
-    exit 1
+	echo `basename "$prog"`": can't find $jarfile"
+	exit 1
 fi
 
 javaOpts=""
@@ -63,9 +63,9 @@ javaOpts="-Xmx512M"
 # add a command-line parameter such as "-JXmx256M" in your ant scripts, for
 # example.
 while expr "x$1" : 'x-J' >/dev/null; do
-    opt=`expr "$1" : '-J\(.*\)'`
-    javaOpts="${javaOpts} -${opt}"
-    shift
+	opt=`expr "$1" : '-J\(.*\)'`
+	javaOpts="${javaOpts} -${opt}"
+	shift
 done
 
 if [ "$OSTYPE" = "cygwin" ] ; then
